services:
  - type: web
    name: jawebni-insta-bot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_PORT
        value: "10000"
      - key: PORT
        value: "10000"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PROTOCOL
        value: "https"
      - key: N8N_EDITOR_BASE_URL
        value: "https://jawebni-insta-bot.onrender.com/"
      - key: WEBHOOK_URL
        value: "https://jawebni-insta-bot.onrender.com/"
      - key: EXECUTIONS_PROCESS
        value: "main"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=400"
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "false"
